package com.bb1.api.commands;

import java.util.Set;

import com.bb1.api.commands.tab.ITabable;

public abstract class Command implements CommandHandler {
	
	public abstract String getName();
	
	public abstract String getDescription();
	
	public String getCommandUsageAutoGenerated() {
		String s = "/"+getName();
		if (getParams()==null || getParams().length==0) {
			return s;
		}
		for (ITabable tab : getParams()) {
			s += " <"+tab.getTabableName()+">";
		}
		return s;
	}
	
	@Deprecated
	public String getCommandUsage(){ return null; };
	
	public Set<String> getAliases() { return null; }
	
	public String getPermission() { return null; }
	
	public boolean isPlayerOnlyCommand() { return false; }
	
	public ITabable[] getParams() { return null; }
	
	// REGISTERING STUFF
	
	public void register() {
		CommandManager.get().registerCommand(this);
	}
	
}
